config/routes.rb
Rails.application.routes.draw do

  

	resources :articles
	resources :users
	resources :mapdemo
	resources :posts
	resources :tasks
	resources :fmaps

  	root 'welcome#index'
   
	get "/log-in" => "sessions#new"
	post "/log-in" => "sessions#create"
	get "/log-out" => "sessions#destroy", as: :log_out
	
	get '/about' => 'fmaps#about'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/fmap.rb
class Fmap < ActiveRecord::Base
	validates :title, presence: true
end

app/models/mapdemo.rb
class Mapdemo < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessor :password
validates_confirmation_of :password
before_save :encrypt_password
def encrypt_password
	self.password_salt = BCrypt::Engine.generate_salt
	self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
end

def self.authenticate(email, password)
user = User.where(email: email).first
if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
user
else
nil
end
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

def new
	if current_user
		@article = Article.new
	else
		redirect_to "/log-in"
	end
end

def create
	if current_user
		@article = Article.new(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	else
		redirect_to "/log-in"
	end
end
 
def show
	if current_user
		@article = Article.find(params[:id])
	else
		redirect_to "/log-in"
	end
end
 
def index
	if current_user
		@articles = Article.all
	else
		redirect_to "/log-in"
	end
end 

def edit
	if current_user
	@article = Article.find(params[:id])
		if current_user.email == @article.user_name
			@article = Article.find(params[:id])
		else
			redirect_to "index"
		end
	else
		redirect_to "/log-in"
	end 
end

def update
	if current_user
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	else
		redirect_to "/log-in"
	end
end

def destroy
	if current_user
		@article = Article.find(params[:id])
		if current_user.email == @article.user_name
			@article.destroy
			redirect_to articles_path
		else
			redirect_to "index"
		end
	else
		redirect_to "/log-in"
	end
end
 
private
  def article_params
    params.require(:article).permit(:title, :text, :user_name)
  end
  

  
end

app/controllers/fmaps_controller.rb
class FmapsController < ApplicationController

def index
	if current_user
		@fmaps = Fmap.all
	else
		redirect_to "/log-in"
	end
end

def about
end

def show
	if current_user
		@fmap = Fmap.find(params[:id])
			if current_user.email == @fmap.username
				gon.id = Fmap.find(params[:id])
			else
				redirect_to "/fmaps"
			end
	else
		redirect_to "/log-in"
	end
end

def new
	if current_user
		@fmap = Fmap.new
	else
		redirect_to "/log-in"
	end
end

def create
	if current_user
		@fmap = Fmap.new(fmap_params)
		if @fmap.save
			redirect_to @fmap
		else
			render 'new'
		end
	else
		redirect_to "/log-in"
	end
end

def update
	if current_user
		@fmap = Fmap.find(params[:id])
		if @fmap.update(fmap_params)
			redirect_to @fmap
		else
			render 'edit'
		end
	else
		redirect_to "/log-in"
	end
end

def destroy
	if current_user
		@fmap = Fmap.find(params[:id])
		if current_user.email == @fmap.username
			@fmap.destroy
			redirect_to fmaps_path
		else
			redirect_to "index"
		end
	else
		redirect_to "/log-in"
	end
end

private
  def fmap_params
    params.require(:fmap).permit(:title, :username, :json, :family, :notes, :extra)
  end



end

app/controllers/mapdemo_controller.rb
class MapdemoController < ApplicationController

def index
  @mapdemo = Mapdemo.new(params[:mapdemo])
 
  @mapdemo.save
  #redirect_to index
	
end


def new
end

def show

end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :all_tasks, only: [:index, :create, :update, :destroy]
  before_action :set_tasks, only: [:edit, :update, :destroy]
	

  # index action has been removed


  def new
    @task = Task.new
  end

  def create
    @task  = Task.create(task_params)
  end

def home
end

def update
    @task.update_attributes(task_params)
end

def destroy
    @task.destroy
	redirect_to tasks_path
end

def show
	gon.id = Task.find(params[:id])
end

  private

    def all_tasks
      @tasks = Task.all
    end

    def set_tasks
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:description, :deadline)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def create
	@user = User.new(user_params)
	if @user.save
		flash[:notice] = "Welcome to the site!"
		redirect_to "/"
	else
		flash[:alert] = "There was a problem creating your account. Please try again."
		redirect_to :back
end
end


private

def user_params
params.require(:user).permit(:email, :password, :password_confirmation)
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/fmaps_helper.rb
module FmapsHelper
end

app/helpers/mapdemo_helper.rb
module MapdemoHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/testa_helper.rb
module TestaHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  
   <p>
    <%= f.label :user_name %><br>
	<%= f.text_field :user_name, readonly: true %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>
<%= link_to 'Log Out', {:controller => 'sessions', :action => 'destroy'} %>

<%= current_user.email %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
	<th>Owner</th>
    <th colspan="3"></th>
  </tr>
 
<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
	<td><%= article.user_name %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= link_to 'Log Out', {:controller => 'sessions', :action => 'destroy'} %>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  
   <p>
    <%= f.label :user_name %><br>
	<%= f.text_field :user_name, :value => current_user.email, readonly: true %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', articles_path %> |
<%= link_to 'Log Out', {:controller => 'sessions', :action => 'destroy'} %> |
<%= current_user.email %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user_name%>
</p>

<%= link_to 'Back', articles_path %>
| <%= link_to 'Edit', edit_article_path(@article) %>
| <%= link_to 'Log Out', {:controller => 'sessions', :action => 'destroy'} %>

app/views/fmaps/about.html.erb
<link rel="stylesheet" href="https://dl.dropboxusercontent.com/u/43615815/CSS/bootstrap.css"> 

<style>
  body {}
  h1   {}
  p    {}
  #content{ padding: 20px; margin: 10px; }
</style>

<div id="content">
<h2>About</h2>
<p>
Typical practice of a working psychiatrist includes individual or group therapy to further understand what is behind certain behavior. When a psychiatrist is in therapy their patients, it can be very useful to be able to map actions, emotions, that typically leads to this behavior. The Family Mapping Project is a software solution to aid in the mapping of actions and emotions. The psychiatrist we are working with directly is Dr. Mike Liepman, though the software is designed to be used by any certified psychiatrist, therapist, or psychologist.
</p>
<p>So we developed a family interactive map program for the esteemed medical professional Dr. Liepman. This program would be used to help those with a history of substance abuse recognize patterns that lead to their abuse.</p>
<p>
The Family interactive map is an interactive tool designed to help victims of substance abuse. In the map, different shapes represent different states or actions. For example, rectangles represent thoughts or perceptions, diamonds represent feelings, and ovals represent actions and behaviors. Arrows are used to show the sequence of events, allowing the user to follow the actions or thoughts from one to another. As well, the map contains a line in the center. This line represents the crossover point between being clean and abusing substances. Any action or thought below the line is one that was made under the influence of a substance. By tracing the thoughts and actions of individuals or families, the professional can help families break out of cycles of substance abuse.

</p>
</div>

app/views/fmaps/index.html.erb
<link rel="stylesheet" href="https://dl.dropboxusercontent.com/u/43615815/CSS/bootstrap.css"> 
<h1>Index</h1>
<%= link_to 'New Family Map', new_fmap_path %>
<table class="table table-hover">
    <tr>
    <th>Title</th>
	<th>User</th>
	<th>Family</th>
    <th>Notes</th>
	<th>Extra</th>
	<th>Load</th>
	<th>Delete</th>
    <th colspan="8"></th>
  </tr>
 
<% @fmaps.each do |fmap| %>
	<% if fmap.username == current_user.email %>
  <tr>
    <td><%= fmap.title %></td>
	<td><%= fmap.username %></td>
	<td><%= fmap.family %></td>
    <td><%= fmap.notes %></td>
	<td><%= fmap.extra %></td>
    <td><%= link_to 'Load', fmap_path(fmap) %></td>
	<td><%= link_to 'Delete', fmap_path(fmap),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
	<% end %>
<% end %>
</table>

app/views/mapdemo/index.html.erb
<!DOCTYPE html>
<html>
<head>



<style>
@import "http://fonts.googleapis.com/css?family=Raleway";
/*----------------------------------------------
CSS settings for HTML div Exact Center
------------------------------------------------*/
#abc {
width:100%;
height:100%;
opacity:.95;
top:0;
left:0;
display:none;
position:fixed;
background-color:#313131;
overflow:auto
}
img#close {
position:absolute;
right:-14px;
top:-14px;
cursor:pointer
}
div#popupContact {
position:absolute;
left:50%;
top:17%;
margin-left:-202px;
font-family:'Raleway',sans-serif
}
form {
max-width:300px;
min-width:250px;
padding:10px 50px;
border:2px solid gray;
border-radius:10px;
font-family:raleway;
background-color:#fff
}
p {
margin-top:30px
}
h2 {
background-color:#FEFFED;
padding:20px 35px;
margin:-10px -50px;
text-align:center;
border-radius:10px 10px 0 0
}
hr {
margin:10px -50px;
border:0;
border-top:1px solid #ccc
}
input[type=text] {
width:82%;
padding:10px;
margin-top:30px;
border:1px solid #ccc;
padding-left:40px;
font-size:16px;
font-family:raleway
}
#name {
background-image:url(../images/name.jpg);
background-repeat:no-repeat;
background-position:5px 7px
}
#email {
background-image:url(../images/email.png);
background-repeat:no-repeat;
background-position:5px 7px
}
textarea {
background-image:url(../images/msg.png);
background-repeat:no-repeat;
background-position:5px 7px;
width:82%;
height:95px;
padding:10px;
resize:none;
margin-top:30px;
border:1px solid #ccc;
padding-left:40px;
font-size:16px;
font-family:raleway;
margin-bottom:30px
}
#submit {
text-decoration:none;
width:100%;
text-align:center;
display:block;
background-color:#FFBC00;
color:#fff;
border:1px solid #FFCB00;
padding:10px 0;
font-size:20px;
cursor:pointer;
border-radius:5px
}
span {
color:red;
font-weight:700
}
button {
height:45px;
border-radius:3px;
background-color:#cd853f;
color:#fff;
font-family:'Raleway',sans-serif;
font-size:18px;
cursor:pointer
}
</style>
</head>

<body id="body" style="overflow:hidden;">
<button type="button" id="undo">Undo</button>
<button type="button" id="redo">Redo</button>
<!-- <button type="button" id="save">Save</button>
<button type="button" id="load">Load</button> -->
<button onclick="serialize_graph()">Save</button>
<button onclick="deserialize_graph()">Load</button>

<p>Double Click shape to edit.</p>
<div id="paper"> </div>
<div id="abc">
<!-- Popup Div Starts Here -->
<div id="popupContact">
<!-- Contact Us Form -->
<form action="#" id="form" method="post" name="form">
<img id="close" src="https://dl.dropboxusercontent.com/u/43615815/close.png" onclick ="div_hide()">
<h2>Box Info:</h2>
<hr>Text:
<input id="name" name="name" placeholder="Name" type="text">
<a id="submit" onClick="div_hide()">Update</a>
</form>
</div>
<!-- Popup Div Ends Here -->
</div>
<script>
var uID;
var jsonString;
var graph = new joint.dia.Graph;

var paper = new joint.dia.Paper({
    el: $('#paper'),
    width: 800,
    height: 600,
    gridSize: 1,
    model: graph
});

var commandManager = new joint.dia.CommandManager({ graph: graph });

var erd = joint.shapes.erd;

var element = function(elm, x, y, label) {
    var cell = new elm({ position: { x: x, y: y }, attrs: { text: { text: label }}});
    graph.addCell(cell);
    return cell;
};
var myLink;
var link = function(elm1, elm2) {
    myLink = new erd.Line({ source: { id: elm1.id }, target: { id: elm2.id }, 
		connector: { name: 'smooth' },
		attrs: {
        '.connection': {
            stroke: '#333333',
            'stroke-width': 3
        },
        '.marker-target': {
            fill: '#333333',
            d: 'M 10 0 L 0 5 L 10 10 z'
        }
    }
		});
    graph.addCell(myLink);
    return myLink;
};

var myLink2;
var link2 = function(elm1, elm2) {
    myLink2 = new erd.Line({ source: { id: elm1.id }, target: { id: elm2.id }, 
		connector: { name: 'smooth' },
		attrs: {
        '.connection': {
            stroke: '#333333',
            'stroke-width': 3
        }
    }
		});
    graph.addCell(myLink2);
    return myLink2;
};

var rec1 = element(erd.Entity, 10, 125, "Sally sees dirty dishes");//rectangle
var rec2 = element(erd.Entity, 170, 100, "Bill hates doing dishes");
var rec3 = element(erd.Entity, 340, 100, "He's mad");
var rec4 = element(erd.Entity, 450, 200, "He will smoke pot");

var rec6 = element(erd.Entity, 225, 10, "I hate doing dishes");//rectangle
var rec7 = element(erd.Entity, 630, 25, "I want a joint");
var rec8 = element(erd.Entity, 20, 515, "She needs a joint");
var rec9 = element(erd.Entity, 630, 100, "Stash is in the garage");
var rec10 = element(erd.Entity, 480, 530, "I'll stay until she is calm");
var rec11 = element(erd.Entity, 300, 530, "Hears Sally's anger");

var dia1 = element(erd.Relationship, 0, 10, "Angry");//diamond
var dia2 = element(erd.Relationship, 220, 200, "Angry");
var dia3 = element(erd.Relationship, 250, 430, "Calm");

var dia4 = element(erd.Relationship, 400, 10, "Angry");
var dia5 = element(erd.Relationship, 200, 515, "Worried");

var ov1 = element(erd.Normal, 100, 5, "Orders Bill wash");//oval
var ov2 = element(erd.Normal, 320, 200, "Yells don't smoke");
var ov3 = element(erd.Normal, 320, 300, "Goes to garage");
var ov10 = element(erd.Normal, 150, 357, "Puffs joint");

var ov4 = element(erd.Normal, 500, 25, "Grimaces");
var ov5 = element(erd.Normal, 650, 175, "Goes to garage");
var ov6 = element(erd.Normal, 650, 250, "Ignores Sally");
var ov7 = element(erd.Normal, 650, 530, "Puffs joint");
var ov8 = element(erd.Normal, 50, 430, "Offers joint");
var ov9 = element(erd.Normal, 50, 357, "Puffs joint");

//#0099FF//blue
//#33CC33//green
rec11.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
});
rec11.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
}); 
rec10.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
}); 
rec9.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
}); 
rec8.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
}); 
rec7.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
}); 
rec6.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
});
dia4.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
}); 
dia5.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
});
ov4.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
});
ov5.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
});  
ov6.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
});  
ov7.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
});  
ov8.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
});  
ov9.attr({
    '.outer': { fill: '#33CC33', stroke: '#29A329' }//green
});     
////////////////////////////////////////////////////////////
rec1.attr({
    '.outer': { fill: '#00CCFF', stroke: '#00A3CC' }//green
}); 
rec2.attr({
    '.outer': { fill: '#00CCFF', stroke: '#00A3CC' }//green
}); 
rec3.attr({
    '.outer': { fill: '#00CCFF', stroke: '#00A3CC' }//green
}); 
rec4.attr({
    '.outer': { fill: '#00CCFF', stroke: '#00A3CC' }//green
}); 
ov1.attr({
    '.outer': { fill: '#00CCFF', stroke: '#00A3CC' }//green
}); 
ov2.attr({
    '.outer': { fill: '#00CCFF', stroke: '#00A3CC' }//green
}); 
ov3.attr({
    '.outer': { fill: '#00CCFF', stroke: '#00A3CC' }//green
});
ov10.attr({
    '.outer': { fill: '#00CCFF', stroke: '#00A3CC' }//green
});  
dia1.attr({
    '.outer': { fill: '#00CCFF', stroke: '#00A3CC' }//green
}); 
dia2.attr({
    '.outer': { fill: '#00CCFF', stroke: '#00A3CC' }//green
}); 
dia3.attr({
    '.outer': { fill: '#00CCFF', stroke: '#00A3CC' }//green
}); 


link(rec1,dia1);
link(dia1,ov1);
link(ov1,rec6);
link(ov1,rec2);
link(rec6,dia4);
link(dia4,ov4);
link(ov4,rec7);
link(rec7,rec9);
link(rec9,ov5);
link(ov5,ov6);
link(ov6,ov7);
link(ov7,rec10);
link(rec10,rec11);
link(rec11,dia5);
link(dia5,rec8);
link(rec8,ov8);
link(ov8,ov9);
link(rec2,rec3);
link(rec3,rec4);
link(rec4,ov2);
link(ov2,dia2);
link(dia2,ov3);
link(ov3,dia3);
link(dia3,ov10);

link2(rec3,ov4);
link2(ov3,rec11);
link2(dia3,ov8);

$('#undo').on('click', _.bind(commandManager.undo, commandManager));
$('#redo').on('click', _.bind(commandManager.redo, commandManager));



function changeText(){
var textBoxText = document.getElementById("textBox").value;
employee.attr({
    text: { text: textBoxText}
});
}

paper.on('cell:pointerdblclick', 
    function(cellView, evt, x, y) { 
		var elm = graph.getCell(cellView.model.id);
		var txt = elm.attr('text/text');
		document.getElementById("name").value = txt;
		uID = cellView.model.id;
		div_show();
        //alert('cell view ' + cellView.model.id + ' was clicked \r\n It contains the text: ' + txt);
    }
);

function changeText2(){
var textBoxText = document.getElementById("name").value;
var elm = graph.getCell(uID);
elm.attr({
    text: { text: textBoxText}
});
}

//Function To Display Popup
function div_show() {
document.getElementById('abc').style.display = "block";
}
//Function to Hide Popup
function div_hide(){
document.getElementById('abc').style.display = "none";
changeText2();
}

//Function to serialize graph
function serialize_graph(){
jsonString = JSON.stringify(graph.toJSON());
console.log(jsonString);
}

//Function to deserialize graph
function deserialize_graph(){
graph.fromJSON(JSON.parse(jsonString));
}
</script>

</body>
</html>

app/views/mapdemo/show.html.erb
<h1>HEY</h1>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/tasks/_task.html.erb
  <%= link_to edit_task_path(task), remote: true do %>
    <button>Edit</button>
  <% end %>

<%= link_to task, remote: true, method: :delete,  data: { confirm: 'Are you sure?' } do %>
  <button>Delete!</button>
<% end %>

app/views/tasks/create.html.erb
<script>
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);
</script>

app/views/tasks/index.html.erb
<h1> Hello </h1>




<%= link_to 'New Task', new_task_path, remote: true %>

<div id="task-form" style="display:none;"></div>

<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <h2>Tasks</h2>
  </div>

  <div class="col-md-2 col-md-offset-4">
    <%= link_to new_task_path, remote: true do %>
      <button class="btn btn-default">New</button>
    <% end %>
  </div>
</div>

<table>
<% @tasks.each do |task| %>
	<tr>
	<td><%= task.description %></td>
	<td><%= task.deadline %></td>
	<td><%= link_to edit_task_path(task), remote: true do %> <button>Edit</button><% end %></td>
	<td><%= link_to task, remote: true, method: :delete,  data: { confirm: 'Are you sure?' } do %><button>Delete!</button><% end %></td>
    <td><%= button_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<td><%= link_to 'Show', task_path(task) %></td>
	</tr>
<% end %>
</table>


<div class="row">
  <div class="col-md-6 col-md-offset-2" id="task-form" style="display:none;"></div>
</div>

<div class="row">
  <div class="col-md-7 col-md-offset-1" id="tasks"><%= render @tasks %></div>
</div>

<%= content_tag "div", id: "products", data: {url: Task.limit(10) } do %>
  Loading products...
<% end %>

<script>
$( document ).ready(function() {
    console.log $('#products').data('url');
});

</script>